# Generated by Django 5.0.2 on 2024-03-09 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
