# Generated by Django 5.0.2 on 2024-03-14 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='locally',
            new_name='locality',
        ),
    ]
