# Generated by Django 5.0.2 on 2024-03-16 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_john'),
    ]

    operations = [
        migrations.DeleteModel(
            name='john',
        ),
    ]
