# Generated by Django 5.0.2 on 2024-03-16 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_delete_john'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='slug',
            field=models.SlugField(default='', unique=False),
        ),
    ]
