# Generated by Django 5.0.2 on 2024-03-16 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_book_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='slug',
        ),
    ]
