# Generated by Django 5.0.2 on 2024-03-16 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0014_remove_book_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
    ]
