# Generated by Django 5.0.2 on 2024-03-20 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0015_book_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_must_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='is_recommended',
            field=models.BooleanField(default=False),
        ),
    ]
