# Generated by Django 5.0.2 on 2024-03-20 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0016_book_is_must_read_book_is_recommended'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookscategory',
            name='description',
        ),
    ]
