# Generated by Django 5.0.2 on 2024-03-21 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0017_remove_bookscategory_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='is_must_read',
        ),
        migrations.RemoveField(
            model_name='book',
            name='is_recommended',
        ),
    ]
