# Generated by Django 5.0.2 on 2024-03-21 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0018_remove_book_is_must_read_remove_book_is_recommended'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='must_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='recommended',
            field=models.BooleanField(default=False),
        ),
    ]
