# Generated by Django 5.0.2 on 2024-03-26 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0021_alter_book_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='biography',
        ),
        migrations.RemoveField(
            model_name='author',
            name='image',
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=230),
        ),
    ]
