# Generated by Django 5.0.4 on 2024-05-02 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0023_author_biography_author_image_alter_author_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='wishlist',
            field=models.ManyToManyField(blank=True, related_name='wishlist_books', to='books.book'),
        ),
    ]
